#pragma once
// Generation-map lineage — the raw material of general ("gen") topological
// naming, and the seed of full coverage for op-GENERATED sub-shapes (fillet
// blends, boolean seams, loft/revolve surfaces) that no sketch scheme can name.
//
// Every modeling operation, when it builds geometry with an OCCT
// BRepBuilderAPI_MakeShape, can report how each OUTPUT sub-shape derives from
// the INPUT via Generated()/Modified()/IsDeleted(). A GenerationLedger records
// that derivation for one op execution. A sub-shape named by its derivation
// ("the face generated by input-edge X") is STABLE across a parameter edit,
// because the derivation STRUCTURE doesn't change even when the geometry moves
// — which is exactly what geometric matching can't guarantee.
//
// The op populates a ledger on every (re)execute; topo::Context carries a
// pointer to the current one, so the "gen" strategy (TopoName.cpp) can mint and
// resolve names through it. Wiring each production op to publish its maps is an
// additive follow-on; this defines the shared vocabulary.

#include <TopoDS_Shape.hxx>
#include <TopAbs_ShapeEnum.hxx>
#include <TopTools_IndexedDataMapOfShapeListOfShape.hxx>

class BRepBuilderAPI_MakeShape;

namespace materializr {
namespace topo {

struct GenerationLedger {
    TopoDS_Shape     input;                 // the op's pre-op shape / profile
    TopAbs_ShapeEnum inType = TopAbs_EDGE;  // type of the input sub-shapes tracked
    // input sub-shape -> the output sub-shapes it produced.
    TopTools_IndexedDataMapOfShapeListOfShape generated;
    TopTools_IndexedDataMapOfShapeListOfShape modified;

    // Capture from any builder: for each sub-shape of `in` of type `t`, record
    // what it Generated / was Modified into. Clears any prior contents.
    void capture(BRepBuilderAPI_MakeShape& mk, const TopoDS_Shape& in,
                 TopAbs_ShapeEnum t);
};

} // namespace topo
} // namespace materializr
